// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ywbrsbldjpmtatbvtqiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3YnJzYmxkanBtdGF0YnZ0cWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMjk5MTcsImV4cCI6MjA3NTcwNTkxN30.lyuEoNV1R3vwK8IEa3-qo9jpZWbsVUZC1IpNlu--0mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);